language: php - 7.1 - nightly
env:
- APP_DEBUG=false
script:
- phpunit -c phpunit.xml --coverage-text
addons:
  ssh_known_hosts: 47.93.91.86
after_success:
- ssh root@47.93.91.86 "./webroot/api.jianji.myexist.cn/travis_build.sh"
