language: php
php:
- 7.1
script: phpunit Test.php
before_install:
- openssl aes-256-cbc -K $encrypted_5f7cffe81ccb_key -iv $encrypted_5f7cffe81ccb_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 47.93.91.86\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
  - 'cd /webroot/travist && git pull'
