language: php
  - 7.1
  - nightly
env:
  - APP_DEBUG=false
php:
- 7.1
script: phpunit Test.php
before_install:
- openssl aes-256-cbc -K $encrypted_5f7cffe81ccb_key -iv $encrypted_5f7cffe81ccb_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
addons:
  ssh_known_hosts: 47.93.91.86
after_success:
  - ssh root@47.93.91.86 "./webroot/api.jianji.myexist.cn/gitShell.sh"
